с использованием if
js-tasks-ru/jsbasic-20230428_falsejornal pull request #3
Opened 2023-05-04 09:46 UTC by CondaConda

2023-05-04 09:47 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 10:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-04 10:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-04 10:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-04 12:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-05 10:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-05 10:14 UTC, SinimaWath requested changes

2023-05-05 10:14 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return short_str + '…';
тут можно написать без временной переменной: `return str.slice(0 , --maxlength) + '…'`

2023-05-05 10:14 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  }
В этой задаче и в других, else избыточен, так же не нужно добавлять скобочки в return
```
if (str) {
  return str[0].toUpperCase() + str.slice(1);
}

return str;
```

2023-05-07 08:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-07 09:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-07 11:33 UTC, SinimaWath approved these changes

2023-05-07 11:34 UTC, merged