3/5
js-tasks-ru/jsbasic-20230428_falsejornal pull request #5
Opened 2023-05-17 08:49 UTC by CondaConda

2023-05-17 08:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-17 11:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-17 12:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-18 18:52 UTC, SinimaWath requested changes

2023-05-18 18:52 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return(join);
давай используем здесь map

2023-05-18 18:52 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    .filter((user)=>{return user.age <= age;})
стоит опустить return, если сразу возвращаешь результат: `.filter(user => user.age <= age)`

2023-05-22 08:13 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-23 15:04 UTC, SinimaWath approved these changes

2023-05-23 15:05 UTC, merged